<a href="https://colab.research.google.com/github/ADGGi/CP2/blob/main/prepro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Îç∞Ïù¥ÌÑ∞ ÎÇòÎà†Î≥¥Í∏∞(-> celebÎ≥Ñ ÎåÄÌôîÎç∞Ïù¥ÌÑ∞)

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/CP2/·Ñê·Ö©·Üº·Ñí·Ö°·Ü∏·ÑÜ·ÖÆ·Ü´·Ñâ·Ö•3.csv')

In [ ]:
df.head()

           date   time celeb  ...                       comments file Unnamed: 6
0  Jul 12, 2021  20:39  VAYA  ...                     ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§.  NaN        NaN
1  Jul 12, 2021  20:40  VAYA  ...                          ÏÇ¨ÎûëÌï¥Ïöîüñ§  NaN        NaN
2  Jul 12, 2021  20:40  VAYA  ...                     ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§.  NaN        NaN
3  Jul 12, 2021  20:41  VAYA  ...                     ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§.  NaN        NaN
4  Jul 12, 2021  20:41  VAYA  ...  Îã®ÌÜ° Ï†ÑÏö© Ïù∏Ïä§ÌÉÄ ÎåÄÏ≤¥ÏùºÏßÄ... ÏûêÎ†§Í≥†ÌñàÎäîÎç∞ ÌååÎì§..  NaN        NaN

[5 rows x 7 columns]

In [ ]:
df = df[['date', 'time', 'celeb', 'code', 'comments', 'file']]
df

               date   time celeb  code                       comments file
0      Jul 12, 2021  20:39  VAYA  KAMF                     ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§.  NaN
1      Jul 12, 2021  20:40  VAYA  KAMF                          ÏÇ¨ÎûëÌï¥Ïöîüñ§  NaN
2      Jul 12, 2021  20:40  VAYA  MLSC                     ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§.  NaN
3      Jul 12, 2021  20:41  VAYA  ZSOS                     ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§.  NaN
4      Jul 12, 2021  20:41  VAYA  MLSC  Îã®ÌÜ° Ï†ÑÏö© Ïù∏Ïä§ÌÉÄ ÎåÄÏ≤¥ÏùºÏßÄ... ÏûêÎ†§Í≥†ÌñàÎäîÎç∞ ÌååÎì§..  NaN
...             ...    ...   ...   ...                            ...  ...
10328           NaN    NaN   NaN   NaN                            NaN  NaN
10329           NaN    NaN   NaN   NaN                            NaN  NaN
10330           NaN    NaN   NaN   NaN                            NaN  NaN
10331           NaN    NaN   NaN   NaN                            NaN  NaN
10332           NaN    NaN   NaN   NaN                            NaN  NaN

[10333 rows x 6 columns]

In [ ]:
df = df[1:10327]

In [ ]:
df['celeb'].unique()

array(['VAYA', 'WKDG', 'XMSQ', 'CJSL', 'DQZB', 'JLDN', 'OSQR', 'JSEU',
       'LOVM', 'JOPU'], dtype=object)

In [ ]:
celeb_VAYA = df[df['celeb']=='VAYA']
celeb_VAYA.reset_index(drop=True, inplace=True)
celeb_VAYA

              date  ... file
0     Jul 12, 2021  ...  NaN
1     Jul 12, 2021  ...  NaN
2     Jul 12, 2021  ...  NaN
3     Jul 12, 2021  ...  NaN
4     Jul 12, 2021  ...  NaN
...            ...  ...  ...
3037  Aug 19, 2021  ...  NaN
3038  Aug 19, 2021  ...  NaN
3039  Aug 19, 2021  ...  NaN
3040  Aug 19, 2021  ...  NaN
3041  Aug 19, 2021  ...  NaN

[3042 rows x 6 columns]

In [ ]:
celeb_WKDG = df[df['celeb']=='WKDG']
celeb_WKDG.reset_index(drop=True, inplace=True)
celeb_WKDG

              date  ...                  file
0      Jul 9, 2021  ...                   NaN
1      Jul 9, 2021  ...  ÌååÏùº_1625760471882.mov
2      Jul 9, 2021  ...                   NaN
3      Jul 9, 2021  ...                   NaN
4      Jul 9, 2021  ...                   NaN
...            ...  ...                   ...
1710  Aug 19, 2021  ...                   NaN
1711  Aug 19, 2021  ...                   NaN
1712  Aug 19, 2021  ...                   NaN
1713  Aug 19, 2021  ...                   NaN
1714  Aug 19, 2021  ...                   NaN

[1715 rows x 6 columns]

In [ ]:
celeb_XMSQ = df[df['celeb']=='XMSQ']
celeb_XMSQ.reset_index(drop=True, inplace=True)
celeb_XMSQ

              date   time celeb  code            comments file
0      Jul 8, 2021  21:04  XMSQ  BYZG     ÏΩîÍ∞ÄÏø®Îùº ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§.  NaN
1      Jul 8, 2021  21:36  XMSQ  BYZG        „Öé„Öá„Öé„Öá ÏïàÎÖïÌïòÏÑ∏Ïöî~?  NaN
2      Jul 8, 2021  21:49  XMSQ  XMSQ       OperatorÏïàÎÖïÌïòÏÑ∏Ïö©  NaN
3      Jul 8, 2021  21:56  XMSQ  BYZG  Ïù¥Ï†ú Ïû•ÎßàÏù∏Îç∞ Ïû†Ïù¥ ÏïàÏò§ÎÑ§Ïöî „Ö†„Ö†  NaN
4      Jul 8, 2021  22:00  XMSQ  LBLA          ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§.  NaN
...            ...    ...   ...   ...                 ...  ...
2280  Aug 19, 2021  11:48  XMSQ  JPGP         Ïò§ÎäòÏùÄ Í±∞ÎûòÌï†ÏàòÏûàÏùÑÍπå  NaN
2281  Aug 19, 2021  11:49  XMSQ  ZRAJ              ÏâêÏù¥ÌÇ∑ÏâêÏù¥ÌÇ∑  NaN
2282  Aug 19, 2021  11:50  XMSQ  WSFL       Ïò§„Öã„Öã„Öã„Öã ÎÖπÏ∞®Îßõ ÏâêÏù¥ÌÅ¨  NaN
2283  Aug 19, 2021  11:50  XMSQ  WSFL       Ïù¥Ï†ú Ïä§ÌååÎ•¥ÌÉÑÌÅêÎßå Ï°∞ÏßÄÎ©¥  NaN
2284  Aug 19, 2021  11:50  XMSQ  XMSQ    OperatorÎ≤†Í∞úÎèÑ ÌåîÏïÑÏïºÎåê  NaN

[2285 rows x 6 columns]

In [ ]:
celeb_CJSL = df[df['celeb']=='CJSL']
celeb_CJSL.reset_index(drop=True, inplace=True)
celeb_CJSL

              date   time  ...                        comments               file
0     Jun 12, 2021  23:15  ...                   OperatorÏïàÎÖïÌïòÏÑ∏Ïöî                NaN
1     Jun 12, 2021  23:16  ...    OperatorÏñºÎ¶¨Ïñ¥ÎãµÌÑ∞Î∂ÑÎì§ ÎëêÎ∂ÑÎßåÏù¥ ÏÉàÎ°ú ÍπåÏÖ®Íµ∞Ïöî                NaN
2     Jun 12, 2021  23:16  ...                             NaN  Img 1623507379998
3     Jun 12, 2021  23:16  ...            OperatorÏöîÏ¶ò ÎßàÎ¶¨ Ï∫£ÌÉÄÏõåÏûÖÎãàÎã§                NaN
4     Jun 12, 2021  23:17  ...                              „Öã„Öã                NaN
...            ...    ...  ...                             ...                ...
1692  Aug 19, 2021  11:18  ...                  15ÌïôÏ†êÎ≥¥Îã§Îäî ÎÇ´Ï£†...?                NaN
1693  Aug 19, 2021  11:32  ...              OperatorÏù¥Í≤åÎ™®Îûå!„Öã„Öã Ïª§ÏóΩ                NaN
1694  Aug 19, 2021  11:34  ...                   Í∑ÄÏóΩÎÑ§Ïöî ÎßàÏπò Ï†ÄÏ≤òÎüº „Öé                NaN
1695  Aug 19, 2021  11:34  ...                           Ïñ¥Îßõ„Öã„Öã„Öã                NaN
1696  Aug 19, 2021  11:41  ...  ÏãúÏßÄÎπÑÏóêÏÑú ÌååÎäî ÌåùÏΩòÏΩ§Î≥¥ÏÑ∏Ìä∏Ïöî... 35000ÏõêÏù∏Í∞Ä..                NaN

[1697 rows x 6 columns]

In [ ]:
celeb_DQZB = df[df['celeb']=='DQZB']
celeb_DQZB.reset_index(drop=True, inplace=True)
celeb_DQZB

             date  ...               file
0     Jul 6, 2021  ...                NaN
1     Jul 6, 2021  ...                NaN
2     Jul 6, 2021  ...                NaN
3     Jul 6, 2021  ...                NaN
4     Jul 6, 2021  ...                NaN
..            ...  ...                ...
307  Aug 10, 2021  ...                NaN
308  Aug 10, 2021  ...                NaN
309  Aug 10, 2021  ...                NaN
310  Aug 10, 2021  ...  Img 1628602317413
311  Aug 10, 2021  ...                NaN

[312 rows x 6 columns]

In [ ]:
celeb_JLDN = df[df['celeb']=='JLDN']
celeb_JLDN.reset_index(drop=True, inplace=True)
celeb_JLDN

             date   time celeb  code                  comments file
0     Jul 7, 2021  14:45  JLDN  CNJO                ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§.  NaN
1     Jul 7, 2021  14:45  JLDN  CNJO                    Ïù¥Î¶¨Ïò§ÎÑàÎùº~  NaN
2     Jul 7, 2021  14:45  JLDN  JLDN        Operator„Öã„Öã„Öã„Öã„Öã„Öã„Öã„Öã„Öã„Öã  NaN
3     Jul 7, 2021  14:45  JLDN  JLDN            Operator1Îπ† ÎÇòÏù¥Ïä§  NaN
4     Jul 7, 2021  14:46  JLDN  CNJO                      „Ñ¥„Öá„ÖÖ~  NaN
..            ...    ...   ...   ...                       ...  ...
910  Aug 17, 2021  14:18  JLDN  EFYA            Í≥ºÏùåÌïòÏãúÎçîÎãà....ÌïòÌïò..  NaN
911  Aug 17, 2021  14:19  JLDN  JLDN        Operator„Öã„Öã„Öã„Öã„ÖãÏïÑ..ÎëêÏïº  NaN
912  Aug 17, 2021  15:38  JLDN  UNGO  ÌëπÏâ¨ÏãúÍ≥† ÏæåÏ∞®ÌïòÏÑ∏Ïöî „Ö†„Öú Í±¥Í∞ïÏù¥ Î®ºÏ†ëÎãàÎã§!!  NaN
913  Aug 18, 2021  12:12  JLDN  JLDN        OperatorÏò§Î±Ö ÏïÑÎßàÎèÑ 1Ïãú!  NaN
914  Aug 18, 2021  12:19  JLDN  CNJO                       ÌôïÏù∏~  NaN

[915 rows x 6 columns]

In [ ]:
celeb_OSQR = df[df['celeb']=='OSQR']
celeb_OSQR.reset_index(drop=True, inplace=True)
celeb_OSQR

            date   time celeb  code         comments file
0    Jul 8, 2021  21:36  OSQR  BYZG  ÏΩîÍ∞ÄÏø®Îùº ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§.  NaN
1    Jul 8, 2021  21:36  OSQR  BYZG          ÏïàÎÖïÌïòÏÑ∏Ïöî~?  NaN
2    Jul 8, 2021  21:46  OSQR  FZOM       ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§.  NaN
3    Jul 8, 2021  21:46  OSQR  FZOM  ÎåÄÏû•Îãò! Ïù∏ÏÇ¨Î∞ïÏäµÎãàÎã§!^^7  NaN
4    Jul 9, 2021  07:03  OSQR  NSMB       ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§.  NaN
..           ...    ...   ...   ...              ...  ...
83  Aug 15, 2021  19:02  OSQR  UPIG       ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§.  NaN
84  Aug 15, 2021  19:03  OSQR  UPIG             Ïö∞ÏôÄÏö∞Ïôï  NaN
85  Aug 15, 2021  19:03  OSQR  UPIG      Ïù¥Í±∏Ïù¥Ï†úÏïåÏïòÎÑ§ ÌïòÏù¥Ïö©  NaN
86  Aug 15, 2021  19:33  OSQR  OSQR    OperatorÏñ¥ÏÑúÏôÄ‚ò∫Ô∏è  NaN
87  Aug 15, 2021  19:56  OSQR  UPIG                üòÅ  NaN

[88 rows x 6 columns]

In [ ]:
celeb_JSEU = df[df['celeb']=='JSEU']
celeb_JSEU.reset_index(drop=True, inplace=True)
celeb_JSEU

            date   time celeb  code                          comments file
0   Aug 13, 2021  15:27  JSEU  NTFC                        ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§.  NaN
1   Aug 13, 2021  15:29  JSEU  NTFC            Ïñ¥ÎñªÍ≤å ÎÇòÏò§ÎäîÏßÄ Í∂ÅÍ∏àÌï¥ÏÑú Ï≥êÎ≥¥Îäî ÏïÑÎ¨¥Îßê!  NaN
2   Aug 13, 2021  16:46  JSEU  JSEU                Operator {ÎãâÎÑ§ÏûÑ}Îãò Î∞îÎ≥¥  NaN
3   Aug 13, 2021  16:57  JSEU  NQWK                                 Ïïç  NaN
4   Aug 13, 2021  16:57  JSEU  NQWK                                 „Ö†  NaN
5   Aug 13, 2021  17:05  JSEU  CIUI                               „Öá„ÖÅ„Öá  NaN
6   Aug 13, 2021  17:06  JSEU  CIUI                   ÏïåÎ¶ºÏù¥ Ï£ÑÎã§ ÏïàÏö∏Î†∏ÏùçÎãàÎã§..  NaN
7   Aug 13, 2021  18:37  JSEU  NTFC                               ‡≤†Ô∏µ‡≤†  NaN
8   Aug 13, 2021  18:39  JSEU  BGGQ                                 ?  NaN
9   Aug 13, 2021  18:39  JSEU  BGGQ                     Í∞ëÏûêÍ∏∞ Î∞îÎ≥¥Î•º Î∞ïÎäîÎã§Íµ¨?  NaN
10  Aug 13, 2021  18:45  JSEU  JSEU                   OperatorÎ™ΩÏ¥ùÏù¥ „Öé0„Öé  NaN
11  Aug 13, 2021  18:46  JSEU  XLJI                           ÎïÖÍº¨ÎßπÏù¥ „Öå„Öå  NaN
12  Aug 13, 2021  18:52  JSEU  NTFC       ‡≤†Ô∏µ‡≤†‡≤†Ô∏µ‡≤†‡≤†Ô∏µ‡≤†‡≤†Ô∏µ‡≤†‡≤†Ô∏µ‡≤†‡≤†Ô∏µ‡≤†‡≤†Ô∏µ‡≤†‡≤†Ô∏µ‡≤†‡≤†Ô∏µ‡≤†  NaN
13  Aug 13, 2021  18:52  JSEU  NTFC  ÎÇ¥Ïùº Î∞©ÏÜ° Ïïà Í∞àÍ∫ºÏóêÏöî! Ìù•! Í∞ÄÎçîÎùºÎèÑ Ï°∞Ïö©Ìûà ÏûàÏñ¥ÏïºÍ≤†Îã§!  NaN
14  Aug 13, 2021  19:24  JSEU  JSEU         OperatorÏ†ÄÌïúÌÖå ÌòëÎ∞ïÏùÄ Ïïà ÌÜµÌï¥Ïöî „Öã0„Öã  NaN
15  Aug 13, 2021  19:42  JSEU  NTFC             ÏïåÏïòÏñ¥Ïöî.. Î™ΩÏ¥ùÏù¥ Ìï†ÍªòÏöî(¬¥;Ô∏µ;`)  NaN
16  Aug 13, 2021  19:43  JSEU  NTFC           Í∑ºÎç∞ ÏÇ¨Ïã§ ÎÇ¥Ïùº ÌïôÏõê ÎïåÎ¨∏Ïóê Î™ªÍ∞ÄÏó¨ „Öã„Öã„Öã  NaN
17  Aug 13, 2021  19:44  JSEU  JSEU                       OperatorÎ™ΩÏ¥ùÏù¥  NaN
18  Aug 13, 2021  19:45  JSEU  NTFC                               Î™ΩÏ¥ùÏù¥  NaN
19  Aug 13, 2021  20:41  JSEU  CIUI                              ÏûòÏûêÏöîÏò§  NaN
20  Aug 14, 2021  07:39  JSEU  NTFC                           ÍµøÎ™®ÎãùÏù¥ÏóêÏöî!  NaN
21  Aug 14, 2021  11:21  JSEU  CIUI                          Ïûò Ï£ºÎ¨¥ÏÖ®ÎÇòÏöîÏò§  NaN
22  Aug 14, 2021  11:21  JSEU  CIUI                         Ï¢ãÏùÄ ÏïÑÏπ®ÏûÑÎãàÎã§!  NaN
23  Aug 14, 2021  15:06  JSEU  SBBO                        ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§.  NaN
24  Aug 14, 2021  19:28  JSEU  GXIX                         ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§  NaN
25  Aug 15, 2021  06:25  JSEU  CYRB                        ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§.  NaN
26  Aug 15, 2021  19:09  JSEU  JSEU                      OperatorÏ´ÄÏïÑÏ´ÄÏïÑ  NaN
27  Aug 15, 2021  19:10  JSEU  CIUI       „ÖÅ..Î™©Ïù¥ „ÖÖ..Ïâ∞ Î∞ò„Ñ¥Îãò...Ïù¥Îùº..ÎèÑ Ï¢ãÏïÑÏöîÏò§  NaN
28  Aug 15, 2021  19:18  JSEU  XLJI                                Ï´ÄÏ†Ä  NaN
29  Aug 15, 2021  19:25  JSEU  NQWK                            ÏïÑÎ¨¥Ìäº Ï´ÄÏïÑ  NaN
30  Aug 15, 2021  19:34  JSEU  BGGQ              7Ïãú,,Ïóê Ï´ÄÏïÑÎ•º Î∞ïÏúºÏã†Îã§Í∑úÏöî? „Öã„Öã  NaN
31  Aug 16, 2021  18:14  JSEU  XLJI                          Î∞òÎãòÎ∞îÎ≥¥ („Öå„Öå  NaN
32  Aug 17, 2021  00:02  JSEU  NTFC                     Î™© Îπ†ÏßÄÍ≤å Í∏∞Îã§Î¶¨ÎäîÏ§ë..  NaN
33  Aug 17, 2021  01:29  JSEU  NTFC                       -Ìä∏Ïàò ÏßÄÏ≥ê Ïû†Îì§Îã§-  NaN
34  Aug 17, 2021  21:38  JSEU  CIUI         Î∞òÎãò„ÖÅ,, Î∞∞ ÏïÑÌîàÍ±∞ Îã§ ÎÇ´Í≥† ÏïÑÌë∏ÏßÄ ÎßôÏãúÎã§„Öè  NaN
35  Aug 17, 2021  22:00  JSEU  JSEU                      OperatorÏùëÏï†..  NaN
36  Aug 17, 2021  22:00  JSEU  JSEU               OperatorÏïÑÍ∞ÄÎ∞ò.. Î∞∞ÏïÑÌåå..  NaN
37  Aug 17, 2021  22:01  JSEU  CIUI                                 Ìûù  NaN
38  Aug 17, 2021  22:01  JSEU  CIUI                           (Ïö∞Îäî ÏûÑÌã∞)  NaN
39  Aug 17, 2021  22:53  JSEU  NQWK                       Ìëπ Ïâ¨ÏÖîÏú†....„Ö†„Ö†  NaN
40  Aug 18, 2021  20:02  JSEU  BGGQ                           Î∞òÎãòÎ∞òÎãò „Ö†„Ö†  NaN
41  Aug 18, 2021  20:02  JSEU  BGGQ                        Ïù¥Ï†úÌá¥Í∑ºÌñàÏñ¥Ïöî „Ö†„Ö†  NaN
42  Aug 18, 2021  20:02  JSEU  BGGQ             Ìä∏ÏàòÍ∞Ä ÎØ∏ÏïàÌï¥Ïöî ÌôîÎÇ¥ÏßÄ ÎßêÏïÑÏ£ºÏÑ∏Ïöî „Ö†„Ö†  NaN
43  Aug 19, 2021  00:12  JSEU  JSEU                     OperatorÌÖÄÎ∏îÎü¨ÏÇøÎã§  NaN
44  Aug 19, 2021  00:26  JSEU  NQWK                                 Ïò§  NaN
45  Aug 19, 2021  00:26  JSEU  NQWK                            Î®∏ ÏÇ¨ÏÖ®ÎÇòÏó¨  NaN
46  Aug 19, 2021  00:41  JSEU  CIUI                        Ïñ¥Îñ§ ÎîîÏûêÏù∏Ïù∏Í∞ÄÏöß!  NaN
47  Aug 19, 2021  01:56  JSEU  BGGQ                      Ïñ¥Îñ§Í±∏Î°ú ÏÉÄÎÇòÏöî? „Öã„Öã  NaN
48  Aug 19, 2021  09:27  JSEU  BYZG                          Ïò§ Ïñ¥Îñ§Í±∞Ïö§??  NaN

In [ ]:
celeb_LOVM = df[df['celeb']=='LOVM']
celeb_LOVM.reset_index(drop=True, inplace=True)
celeb_LOVM

            date   time celeb  code          comments               file
0    Aug 9, 2021  15:26  LOVM  COPY        ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§.                NaN
1    Aug 9, 2021  15:26  LOVM  COPY                 ?                NaN
2    Aug 9, 2021  15:26  LOVM  COPY  ÎÑ§Ïπ¥ÎãòÏù¥ Ïó¨Í∏∞ÏÑú ÏôúÎÇòÏôÄÏöî..?                NaN
3    Aug 9, 2021  15:28  LOVM  COPY               NaN  Img 1628490502045
4    Aug 9, 2021  15:29  LOVM  LOVM         OperatorÌóâ                NaN
..           ...    ...   ...   ...               ...                ...
83  Aug 18, 2021  02:09  LOVM  COPY            ÎßâÎÇ¥ Î°úÏö¥Ïù¥                NaN
84  Aug 18, 2021  02:09  LOVM  COPY               NaN  Img 1629220195753
85  Aug 18, 2021  02:09  LOVM  COPY             ÎëòÏß∏ ÏèòÏïº                NaN
86  Aug 18, 2021  02:10  LOVM  COPY               NaN  Img 1629220215060
87  Aug 18, 2021  02:10  LOVM  COPY             Ï≤´Ïß∏ ÏòπÏù¥                NaN

[88 rows x 6 columns]

In [ ]:
celeb_JOPU = df[df['celeb']=='JOPU']
celeb_JOPU.reset_index(drop=True, inplace=True)
celeb_JOPU

             date  ...               file
0     Aug 7, 2021  ...                NaN
1     Aug 8, 2021  ...                NaN
2    Aug 10, 2021  ...                NaN
3    Aug 10, 2021  ...  Img 1628545098085
4    Aug 10, 2021  ...                NaN
..            ...  ...                ...
130  Aug 18, 2021  ...                NaN
131  Aug 18, 2021  ...                NaN
132  Aug 18, 2021  ...                NaN
133  Aug 18, 2021  ...                NaN
134  Aug 19, 2021  ...                NaN

[135 rows x 6 columns]

In [ ]:
celeb_VAYA.to_csv('/content/drive/MyDrive/CP2/celeb_VAYA.csv')
celeb_WKDG.to_csv('/content/drive/MyDrive/CP2/celeb_WKDG.csv')
celeb_XMSQ.to_csv('/content/drive/MyDrive/CP2/celeb_XMSQ.csv')
celeb_CJSL.to_csv('/content/drive/MyDrive/CP2/celeb_CJSL.csv')
celeb_DQZB.to_csv('/content/drive/MyDrive/CP2/celeb_DQZB.csv')
celeb_JLDN.to_csv('/content/drive/MyDrive/CP2/celeb_JLDN.csv')
celeb_OSQR.to_csv('/content/drive/MyDrive/CP2/celeb_OSQR.csv')
celeb_JSEU.to_csv('/content/drive/MyDrive/CP2/celeb_JSEU.csv')
celeb_LOVM.to_csv('/content/drive/MyDrive/CP2/celeb_LOVM.csv')
celeb_JOPU.to_csv('/content/drive/MyDrive/CP2/celeb_JOPU.csv')

#ÌÖçÏä§Ìä∏ Ï†ÑÏ≤òÎ¶¨

In [ ]:
df.dtypes

date        object
time        object
celeb       object
code        object
comments    object
file        object
dtype: object

In [ ]:
import re

In [ ]:
def clean(text) :
  #ÌïúÍµ≠Ïñ¥ÏôÄ ÏïåÌååÎ≤≥Îßå ÎÇ®Í∏∞Í≥† Ï†úÍ±∞
  #4Î≤à Ïù¥ÏÉÅ Î∞òÎ≥µÎêòÎäî Î¨∏ÏûêÎäî 2Í∏ÄÏûêÎßå ÎÇ®ÍπÄ
  #2Ïπ∏Ïù¥ÏÉÅ Í≥µÎ∞±ÏùÄ 1Ïπ∏Îßå ÎÇ®ÍπÄ
  pattern1 = re.compile(r"[^ A-Za-z0-9Í∞Ä-Ìû£]+")
  pattern2 = re.compile(r"(.)\1{2,}")
  pattern3 = re.compile(r"\s+")

  text = pattern1.sub("", str(text))
  text = pattern2.sub(r"\1" * 2, str(text))
  text = pattern3.sub(" ", str(text))

  return text.strip()

In [ ]:
celeb_VAYA['comments']

0                                                   ÏÇ¨ÎûëÌï¥Ïöîüñ§
1                                              ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§.
2                                              ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§.
3                           Îã®ÌÜ° Ï†ÑÏö© Ïù∏Ïä§ÌÉÄ ÎåÄÏ≤¥ÏùºÏßÄ... ÏûêÎ†§Í≥†ÌñàÎäîÎç∞ ÌååÎì§..
4                                            Ïù¥ ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§.
                              ...
3037                                 ÏïÑÏΩîÏΩî ÏûòÌïòÏÖ®Ïñ¥Ïöî Ïì∞Îã¥Ïì∞Îã§Ïïî üíãüíãüíãüíú
3038                                    ÏûòÌïòÏÖ®Ïñ¥Ïöî Ïì∞Îã¥Ïì∞Îã¥ Ìëπ Ïâ¨ÏÑ∏Ïö•!
3039                                           ÏûòÌïòÏÖ®Ïñ¥Ïöî Ïì∞Îã¥Ïì∞Îã¥
3040                                             ÏïÑÏΩî ÏûòÌïòÏÖ®Ïñ¥Ïöî
3041    ÏïÑÏΩî ÏûòÌïòÏÖ®Ïñ¥Ïöî Î∞∞ÌÜµÌÜµ Ïì∞Îã¥Î¨∏Ïßà \nÏÜåÌôî Ï¢Ä ÎêòÎ©¥ Î™ªÏ£ºÎ¨¥Ïã† Ïû† Ìëπ Ï£ºÎ¨¥ÏÑ∏Ïöî \nÏò§Îäò...
Name: comments, Length: 3042, dtype: object

In [ ]:
celeb_VAYA['comments'] = [clean(c) for c in celeb_VAYA['comments']]
celeb_VAYA['comments']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

0                                                    ÏÇ¨ÎûëÌï¥Ïöî
1                                               ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§
2                                               ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§
3                                Îã®ÌÜ° Ï†ÑÏö© Ïù∏Ïä§ÌÉÄ ÎåÄÏ≤¥ÏùºÏßÄ ÏûêÎ†§Í≥†ÌñàÎäîÎç∞ ÌååÎì§
4                                             Ïù¥ ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§
                              ...
3037                                      ÏïÑÏΩîÏΩî ÏûòÌïòÏÖ®Ïñ¥Ïöî Ïì∞Îã¥Ïì∞Îã§Ïïî
3038                                     ÏûòÌïòÏÖ®Ïñ¥Ïöî Ïì∞Îã¥Ïì∞Îã¥ Ìëπ Ïâ¨ÏÑ∏Ïö•
3039                                           ÏûòÌïòÏÖ®Ïñ¥Ïöî Ïì∞Îã¥Ïì∞Îã¥
3040                                             ÏïÑÏΩî ÏûòÌïòÏÖ®Ïñ¥Ïöî
3041    ÏïÑÏΩî ÏûòÌïòÏÖ®Ïñ¥Ïöî Î∞∞ÌÜµÌÜµ Ïì∞Îã¥Î¨∏Ïßà ÏÜåÌôî Ï¢Ä ÎêòÎ©¥ Î™ªÏ£ºÎ¨¥Ïã† Ïû† Ìëπ Ï£ºÎ¨¥ÏÑ∏Ïöî Ïò§ÎäòÎèÑ ÎßéÏù¥...
Name: comments, Length: 3042, dtype: object

In [ ]:
celeb_VAYA['comments']

0                                                    ÏÇ¨ÎûëÌï¥Ïöî
1                                               ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§
2                                               ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§
3                                Îã®ÌÜ° Ï†ÑÏö© Ïù∏Ïä§ÌÉÄ ÎåÄÏ≤¥ÏùºÏßÄ ÏûêÎ†§Í≥†ÌñàÎäîÎç∞ ÌååÎì§
4                                             Ïù¥ ÎãòÏù¥ Ï∞∏Ïó¨ÌñàÏäµÎãàÎã§
                              ...
3037                                      ÏïÑÏΩîÏΩî ÏûòÌïòÏÖ®Ïñ¥Ïöî Ïì∞Îã¥Ïì∞Îã§Ïïî
3038                                     ÏûòÌïòÏÖ®Ïñ¥Ïöî Ïì∞Îã¥Ïì∞Îã¥ Ìëπ Ïâ¨ÏÑ∏Ïö•
3039                                           ÏûòÌïòÏÖ®Ïñ¥Ïöî Ïì∞Îã¥Ïì∞Îã¥
3040                                             ÏïÑÏΩî ÏûòÌïòÏÖ®Ïñ¥Ïöî
3041    ÏïÑÏΩî ÏûòÌïòÏÖ®Ïñ¥Ïöî Î∞∞ÌÜµÌÜµ Ïì∞Îã¥Î¨∏Ïßà ÏÜåÌôî Ï¢Ä ÎêòÎ©¥ Î™ªÏ£ºÎ¨¥Ïã† Ïû† Ìëπ Ï£ºÎ¨¥ÏÑ∏Ïöî Ïò§ÎäòÎèÑ ÎßéÏù¥...
Name: comments, Length: 3042, dtype: object

In [ ]:
celeb_VAYA

              date  ... file
0     Jul 12, 2021  ...  NaN
1     Jul 12, 2021  ...  NaN
2     Jul 12, 2021  ...  NaN
3     Jul 12, 2021  ...  NaN
4     Jul 12, 2021  ...  NaN
...            ...  ...  ...
3037  Aug 19, 2021  ...  NaN
3038  Aug 19, 2021  ...  NaN
3039  Aug 19, 2021  ...  NaN
3040  Aug 19, 2021  ...  NaN
3041  Aug 19, 2021  ...  NaN

[3042 rows x 6 columns]

In [ ]:
print(len(df[df['code']=='VAYA']))
print(len(df[df['code']!='VAYA']))

336
9990